"""Governance Markdown report (Sprint 20.6 spec section 6).

The report is a read-only snapshot of the corpus through the
governance lens. It includes:

  - total objects
  - objects by identity type
  - objects by trust tier
  - validation failures
  - duplicate candidates
  - promotion candidates (Golden Cases that COULD be promoted)

Architecture boundary: this module reads the corpus, runs the
governance checks, and produces Markdown. It never modifies
the corpus, never talks to retrieval, and never recommends
a design choice. The output is a status report, not a guide."""

from __future__ import annotations

import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from caseos.knowledge.governance.duplicate import (
    detect_duplicates,
)
from caseos.knowledge.governance.trust_tier import (
    TrustTier,
    assign_tiers,
    distribution as tier_distribution,
)
from caseos.knowledge.governance.validator import (
    validate_corpus_for_governance,
)
from caseos.knowledge.governance.promotion import (
    ALLOWED_PROMOTIONS,
)


def _load_all(corpus_dir: Path) -> list[dict]:
    out: list[dict] = []
    if not corpus_dir.exists():
        return out
    for p in sorted(corpus_dir.rglob("*.json")):
        try:
            with p.open("r", encoding="utf-8") as fh:
                data = json.load(fh)
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(data, dict):
            out.append(data)
    return out


def _type_of(ko: dict) -> str:
    ident = str(ko.get("identity") or "")
    return ident.split(".", 1)[0] if "." in ident else "<no-type>"


def _promotion_candidates(kos: list[dict]) -> dict[str, int]:
    "How many KOs of each type COULD be promoted to the",
    "allowed next-stage types. GoldenCases are the main",
    "source of DecisionPattern / FailurePattern /",
    "ExpertPrinciple candidates.",
    out: dict[str, int] = {}
    for ko in kos:
        t = _type_of(ko)
        allowed = ALLOWED_PROMOTIONS.get(t, frozenset())
        for tgt in allowed:
            out[tgt] = out.get(tgt, 0) + 1
    return out


def _build_report(
    corpus_dir: Path,
    kos: list[dict],
    validations,
    duplicates,
    tier_assignments,
    promotion_candidates: dict[str, int],
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    total = len(kos)
    type_counter: Counter = Counter(_type_of(ko) for ko in kos)
    tier_counter = tier_distribution(tier_assignments)
    valid_count = sum(1 for v in validations if v.valid)
    invalid_count = total - valid_count

    L: list[str] = []
    L.append("# Sprint 20.6 -- Corpus Governance Report V1")
    L.append("")
    L.append(f"- **Generated:** {now}")
    L.append(f"- **Corpus root:** " + str(corpus_dir) + "")
    L.append(f"- **Total Knowledge Objects:** {total}")
    L.append(f"- **Governance-valid:** {valid_count}")
    L.append(f"- **Governance-invalid:** {invalid_count}")
    L.append("")
    L.append("This report is generated by backend/caseos/knowledge/governance/report.py.")
    L.append("It is read-only with respect to the corpus, the retrieval engine, the decision engine,")
    L.append("the trust engine, and the recommendation engine.")
    L.append("")

    # Section 1: identity type distribution
    L.append("## 1. Objects by Identity Type")
    L.append("")
    L.append("| Identity Type | Count |")
    L.append("| --- | --- |")
    for t in sorted(type_counter):
        L.append(f"| {t} | {type_counter[t]} |")
    L.append("")

    # Section 2: trust tier distribution
    L.append("## 2. Objects by Trust Tier")
    L.append("")
    L.append("Trust tiers are aligned with ADR-016 Intelligence Trust Model.")
    L.append("is_default=True means the KO did not declare source_reliability and was")
    L.append("tiered by identity-type default.")
    L.append("")
    L.append("| Tier | Count | Default-Assigned |")
    L.append("| --- | --- | --- |")
    for tier in TrustTier:
        count = tier_counter.get(tier.value, 0)
        default_count = sum(
            1 for a in tier_assignments if a.tier == tier and a.is_default
        )
        L.append(f"| {tier.value} | {count} | {default_count} |")
    L.append("")

    # Section 3: validation result
    L.append("## 3. Validation Result")
    L.append("")
    L.append("Each row is one Knowledge Object. OK means the ADR-015 contract")
    L.append("is satisfied AND all governance checks pass. FAIL rows must be")
    L.append("repaired before the object is allowed into the retrieval pool.")
    L.append("")
    L.append("| Status | Identity | Base Missing | Base Errors | Governance Errors |")
    L.append("| --- | --- | --- | --- | --- |")
    for v in validations:
        status = "OK" if v.valid else "FAIL"
        miss = ", ".join(v.base_missing) if v.base_missing else "-"
        berr = "; ".join(v.base_errors) if v.base_errors else "-"
        gerr = "; ".join(v.governance_errors) if v.governance_errors else "-"
        L.append(f"| {status} | {v.identity} | {miss} | {berr} | {gerr} |")
    L.append("")

    # Section 4: duplicate candidates
    L.append("## 4. Duplicate Candidates")
    L.append("")
    if not duplicates:
        L.append("_No duplicate candidates._")
    else:
        L.append(f"**Result: {len(duplicates)} candidate pair(s).**")
        L.append("")
        L.append("| Object A | Object B | Similarity Basis | Reason |")
        L.append("| --- | --- | --- | --- |")
        for d in duplicates:
            L.append(f"| {d.object_a} | {d.object_b} | {", ".join(d.similarity_basis)} | {d.reason} |")
    L.append("")

    # Section 5: promotion candidates
    L.append("## 5. Promotion Candidates")
    L.append("")
    L.append("A KO is a *promotion candidate* when the current corpus contains at")
    L.append("least one object of a type that is allowed to promote to a higher-level")
    L.append("type per ALLOWED_PROMOTIONS. The count is the number of source objects")
    L.append("currently eligible.")
    L.append("")
    if not promotion_candidates:
        L.append("_No promotion candidates._")
    else:
        L.append("| Target Type | Eligible Sources |")
        L.append("| --- | --- |")
        for tgt in sorted(promotion_candidates):
            L.append(f"| {tgt} | {promotion_candidates[tgt]} |")
    L.append("")

    # Section 6: summary
    L.append("## 6. Summary")
    L.append("")
    L.append(f"- Corpus has **{total}** Knowledge Objects.")
    L.append(f"- **{valid_count}** pass governance validation,")
    L.append(f"  **{invalid_count}** require fixes.")
    L.append(f"- **{len(duplicates)}** duplicate candidate pair(s).")
    L.append(f"- **{sum(promotion_candidates.values())}** potential promotion event(s) across {len(promotion_candidates)} target type(s).")
    L.append("")
    if valid_count == total and not duplicates:
        L.append("**Sprint 20.6 acceptance criteria: governance gate green; corpus is clean.**")
    else:
        L.append("**Sprint 20.6 acceptance criteria: governance gate reports issues; see sections above.**")
    L.append("")
    L.append("---")
    L.append("")
    L.append("_End of report._")
    L.append("")
    return chr(10).join(L)



def generate_report(
    corpus_dir: Path | str,
    output_path: Path | str | None = None,
) -> str:
    "Run all governance checks on the corpus and render Markdown.",
    "",
    "If output_path is given, the report is also written to",
    "that path. The Markdown string is always returned.",
    corpus_dir = Path(corpus_dir)
    kos = _load_all(corpus_dir)
    validations = validate_corpus_for_governance(corpus_dir)
    duplicates = detect_duplicates(kos)
    tier_assignments = assign_tiers(kos)
    promotion_candidates = _promotion_candidates(kos)
    md = _build_report(
        corpus_dir, kos, validations, duplicates, tier_assignments, promotion_candidates,
    )
    if output_path is not None:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding="utf-8")
    return md


__all__ = ["generate_report"]
