"""Convert a DecisionContext into a Markdown report.

This generator is deterministic and offline. It produces a single
Markdown document organised as:

  1. Header
  2. Space summary
  3. Inferred decision maker + goals
  4. Selected strategies
  5. Top recommendations
  6. Explanations
  7. Pipeline trace
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.core.decision.context import DecisionContext
    from app.core.decision.models import Recommendation


def render_markdown(context) -> str:
    """Render the full DecisionContext as a Markdown report."""
    sections: list[str] = []
    sections.append(_header(context))
    sections.append(_space_section(context))
    sections.append(_decision_maker_section(context))
    sections.append(_strategy_section(context))
    sections.append(_recommendation_section(context))
    sections.append(_explanation_section(context))
    sections.append(_trace_section(context))
    sections.append(_footer(context))
    return "\n\n".join(s for s in sections if s)


# ----- sections -----

def _header(context) -> str:
    space = context.space_summary
    project = ""
    if space and context.vision_json:
        basic = context.vision_json.get("basic_info", {}) or {}
        project = str(basic.get("project_name", "") or "")
    title = f"# CaseOS Recommendation \u2014 {project}" if project else "# CaseOS Recommendation"
    return f"{title}\n\n_Generated by CaseOS Agent Framework V1._"


def _space_section(context) -> str:
    s = context.space_summary
    if s is None:
        return "## Space\n\n_No space summary available._"
    lines = ["## Space"]
    lines.append(f"- **Site type:** `{s.site_type or 'N/A'}`")
    lines.append(f"- **Inferred domain:** `{s.domain or 'N/A'}`")
    lines.append(f"- **Primary theme:** `{s.primary_theme or 'N/A'}`")
    if s.secondary_themes:
        lines.append(f"- **Secondary themes:** " + ", ".join(f"`{t}`" for t in s.secondary_themes))
    if s.age_groups:
        lines.append(f"- **Age groups:** " + ", ".join(f"`{a}`" for a in s.age_groups))
    if s.functional_units:
        lines.append(f"- **Functional units:** " + ", ".join(f"`{u}`" for u in s.functional_units))
    if s.materials:
        lines.append(f"- **Materials:** " + ", ".join(f"`{m}`" for m in s.materials))
    if s.design_highlights:
        lines.append("- **Design highlights:**")
        for h in s.design_highlights:
            lines.append(f"  - {h}")
    if s.vision_summary:
        lines.append("")
        lines.append("**Vision summary**")
        lines.append(f"> {s.vision_summary}")
    if s.design_interpretation:
        lines.append("")
        lines.append("**Design interpretation**")
        lines.append(f"> {s.design_interpretation}")
    return "\n".join(lines)


def _decision_maker_section(context) -> str:
    dm = context.decision_maker
    if dm is None:
        return "## Decision Maker\n\n_Not inferred._"
    lines = ["## Decision Maker"]
    lines.append(f"- **Profile:** `{dm.profile}`")
    lines.append(f"- **Description:** {dm.description}")
    if dm.rationale:
        lines.append(f"- **Rationale:** {dm.rationale}")
    if context.goals:
        lines.append("")
        lines.append("**Inferred goals**")
        for g in context.goals:
            star = "\u2605" * g.priority
            lines.append(
                f"- {star} `{g.goal_id}` \u2014 {g.name} "
                f"(confidence {g.confidence:.2f})"
            )
    return "\n".join(lines)


def _strategy_section(context) -> str:
    if not context.strategies:
        return "## Strategies\n\n_No strategies selected._"
    lines = ["## Strategies"]
    for s in context.strategies:
        star = "\u2605" * s.priority
        lines.append(f"### {s.name} `{s.strategy_id}` {star}")
        if s.rationale:
            lines.append(f"_{s.rationale}_")
        if s.addresses_goals:
            lines.append(
                "- **Serves goals:** " + ", ".join(f"`{g}`" for g in s.addresses_goals)
            )
        if s.serves_strategies:
            lines.append(
                "- **Synergies:** " + ", ".join(f"`{g}`" for g in s.serves_strategies)
            )
        if s.conflicts_with:
            lines.append(
                "- **Conflicts with:** " + ", ".join(f"`{g}`" for g in s.conflicts_with)
            )
    return "\n".join(lines)


def _recommendation_section(context) -> str:
    if not context.top_recommendations:
        return "## Recommendations\n\n_No top recommendations._"
    lines = ["## Top Recommendations"]
    for r in context.top_recommendations:
        lines.append(f"### #{r.rank} \u2014 {r.name} `{r.object_id}`")
        lines.append(f"- **Score:** {r.score}")
        if r.categories:
            lines.append(
                "- **Category:** " + ", ".join(f"`{c}`" for c in r.categories)
            )
        if r.serves_goals:
            lines.append(
                "- **Serves goals:** " + ", ".join(f"`{g}`" for g in r.serves_goals)
            )
        if r.serves_strategies:
            lines.append(
                "- **Serves strategies:** "
                + ", ".join(f"`{s}`" for s in r.serves_strategies)
            )
        if r.rationale_short:
            lines.append(f"- **Why:** {r.rationale_short}")
    return "\n".join(lines)


def _explanation_section(context) -> str:
    if not context.explanations:
        return "## Explanations\n\n_No explanations generated._"
    lines = ["## Explanations"]
    for exp in context.explanations:
        lines.append(f"### Why `{exp.object_id}`?")
        if exp.patterns:
            lines.append(
                "_Reasoning patterns: " + ", ".join(f"`{p}`" for p in exp.patterns) + "_"
            )
        lines.append("")
        lines.append(exp.text)
    return "\n".join(lines)


def _trace_section(context) -> str:
    if not context.stages:
        return ""
    lines = ["## Pipeline Trace"]
    for s in context.stages:
        duration = context.metadata.get(f"duration.{s.agent}", "?")
        lines.append(
            f"- `{s.agent}` \u2014 {s.status} \u2014 {duration}s"
            + (f" \u2014 {s.note}" if s.note else "")
        )
    return "\n".join(lines)


def _footer(context) -> str:
    return f"---\n\n_Pipeline: {' \u2192 '.join(context.metadata.get('pipeline', []))}_"


__all__ = ["render_markdown"]