"""Intake Markdown report (Sprint 20.7 spec section 6).

The report is a read-only snapshot of the IntakeManager. It includes:

  - total incoming objects
  - status distribution
  - validation results (per case)
  - promotion count
  - rejected count

Architecture boundary: this module reads from the manager. It
does not modify state, does not call retrieval / decision /
trust / recommendation, and does not touch the corpus."""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Optional

from caseos.knowledge.intake.manager import IntakeManager
from caseos.knowledge.intake.status import IntakeStatus


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _build_report(
    manager: IntakeManager,
    recent_transitions: int = 25,
) -> str:
    cases = manager.all_cases()
    counts = manager.status_counts()
    promotions = manager.promotion_events()
    rejected = manager.rejected_count()
    transitions = list(manager._transitions)  # noqa: SLF001 -- report is in-package

    L: list[str] = []
    L.append("# Sprint 20.7 -- Corpus Intake Report V1")
    L.append("")
    L.append(f"- **Generated:** {_now_iso()}")
    L.append(f"- **Total incoming objects:** {len(cases)}")
    L.append(f"- **Promotion count:** {len(promotions)}")
    L.append(f"- **Rejected count:** {rejected}")
    L.append("")
    L.append("This report is generated by ackend/caseos/knowledge/intake/report.py.")
    L.append("It is read-only with respect to the intake manager, governance,")
    L.append("the corpus, the retrieval engine, the decision engine, the trust")
    L.append("engine, and the recommendation engine.")
    L.append("")

    L.append("## 1. Status Distribution")
    L.append("")
    L.append("| Status | Count |")
    L.append("| --- | --- |")
    for s in IntakeStatus:
        L.append(f"| {s.value} | {counts.get(s.value, 0)} |")
    L.append("")

    L.append("## 2. Incoming Objects")
    L.append("")
    if not cases:
        L.append("_No incoming objects yet._")
    else:
        L.append("| ID | Source | Title | Status | Created |")
        L.append("| --- | --- | --- | --- | --- |")
        for c in cases:
            L.append(
                f"| {c.id} | {c.source} | {c.title} | {c.status.value} | {c.created_at} |",
            )
    L.append("")

    L.append("## 3. Recent Transitions")
    L.append("")
    if not transitions:
        L.append("_No transitions recorded._")
    else:
        L.append("| Raw ID | From | To | At | Reason |")
        L.append("| --- | --- | --- | --- | --- |")
        for t in transitions[-recent_transitions:]:
            L.append(
                f"| {t.raw_id} | {t.from_status} | {t.to_status} | {t.at} | {t.reason} |",
            )
    L.append("")

    L.append("## 4. Promotions")
    L.append("")
    if not promotions:
        L.append("_No promotions recorded._")
    else:
        L.append("| Event ID | Source | Target | Trust Tier |")
        L.append("| --- | --- | --- | --- |")
        for ev in promotions:
            L.append(
                f"| {ev.event_id} | {ev.source_identity} | {ev.target_identity} | {ev.trust_tier_at_promotion} |",
            )
    L.append("")

    L.append("## 5. Summary")
    L.append("")
    L.append(f"- **{len(cases)}** total incoming object(s).")
    L.append(f"- **{len(promotions)}** promotion event(s) (raw -> Knowledge Object).")
    L.append(f"- **{rejected}** rejection record(s).")
    L.append("")
    if len(promotions) == 0 and rejected == 0 and len(cases) > 0:
        L.append("No raw case has been promoted or rejected yet; the pipeline is still in intake phase.")
    elif len(promotions) > 0 and rejected == 0:
        L.append("The intake -> governance -> promotion path is working end to end.")
    L.append("")
    L.append("---")
    L.append("")
    L.append("_End of report._")
    L.append("")
    return chr(10).join(L)


def generate_report(
    manager: IntakeManager,
    output_path: Optional[Path | str] = None,
) -> str:
    "Build the intake Markdown report. If output_path is given,",
    "the report is also written to that path.",
    md = _build_report(manager)
    if output_path is not None:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding="utf-8")
    return md


__all__ = ["generate_report"]
